baseURL = "https://www.tclb.cf/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "技術科部"
theme = "tella"
enableRobotsTXT = true
hasCJKLanguage = true
googleAnalytics = "G-FG30LWVSF4"

disqusShortname = "intertech-1"
 
[params]

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "技術科部ロゴ"

  [params.site]
    name = "千葉大学教育学部附属中学校　技術科部"

  [params.homepage_meta_tags]
    meta_description = "Technical Club Official Site"
    meta_og_title = "千葉大学教育学部附属中学校 技術科部"
    meta_og_type = "website"
    meta_og_url = "https://www.tclb.cf"
    meta_og_image = "https://www.tclb.cf/img/tn.png"
    meta_og_description = "Technical Club Official Site"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@tech_chiba"
    meta_twitter_creator = "@tech_chiba"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "企画"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "ブログ"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "技術科部について"
    url = "/about/"
    weight = 3
    
  [[menu.main]]
    identifier = "fes"
    name = "文化祭特設サイト"
    url = "https://fes.tclb.cf"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "お問い合わせ"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "ホーム"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "リポジトリ"
    url = "/repo/"
      weight = 2

  [[menu.footer]]
    name = "中学校公式サイト"
    url = "http://www.jr.chiba-u.jp/"
      weight = 3

[build]
  writeStats = true
