---
label: Products Post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: boolean
  name: featured
  label: featured
- type: number
  name: weight
  label: weight
- type: text
  name: description
  label: description
